name: CI/CD Pipeline

on:
  push:
    branches:
      - master        # Trigger workflow on mainmaster in repo) branch push
      #- '**'        # Trigger workflow on any other branch push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code (clone)
    - name: Checkout code
      uses: actions/checkout@v2

    # Setting up Go environment
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.19' # Specify the Go version you need

    # Cache dependencies (to speed up builds)
    - name: Cache Go modules
      uses: actions/cache@v2
      with:
        path: ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.mod') }}
        restore-keys: |
          ${{ runner.os }}-go-

    # Installing Go dependencies
    - name: Install dependencies
      run: |
        go mod tidy
        go mod vendor

    # Building  the Go application
    - name: Build the Go app
      run: |
        go build -o app main.go

    # Verify build
    - name: Verify build
      run: |
        ./app --version #version flag for testing
